### ISSUE TITLE
how to change filepath for html_table_reporter in reporter options

### ISSUE THREAD

**Issue by DeChrish** [Gauge/html_table_reporter#1]
Mocha options :

config.mochaTest[name] = {
options: {
reporter: 'good-mocha-html-reporter',
timeout: 60000,
logErrors: true,
captureFile: directories.target + '/' + name + '/test-results.html'
}

good-mocha-html-reporter - config file:
module.exports = {
path: '', // full or relative path (relative to your execution folder)
filename: 'report.html',
mode: 'Verbose'
}

When i use 'good-mocha-html-reporter' in mocha options, the report is generated as 'report.html' which is added in reporter-config file.
I want to use captureFile option to save the report file.
Is it possible?

**Comment by Gauge** [comment]
Currently it is not set up to work with the captureFile option. To be
honest i didn't know that such a feature existed. I will look into added
this functionality, as it removes the need to access the module's files to
configure it.

**Comment by pghalliday** [comment]
Hi, just landed here from https://github.com/pghalliday/grunt-mocha-test/issues/103

My recommended change would be to load config overrides from a standard file outside your source (ie. the current working directory). Keeping config inside `node_modules` is problematic as it is often not checked into source code control and even if it were it's likely to be overwritten at some point. Other reporters have used `npm` config in `package.json` but this assumes you will run things with `npm`, so I don't recommend that either.

To use `captureFile` you just need to `console.log` the html output. However you need to not `console.log` anything else or it will also be captured. `captureFile` is necessarily agnostic of they way reporters work, which is why I recommend having reporter specific config for this kind of thing.

**Comment by pghalliday** [comment]
I just remembered another option! A while back `mocha` was changed so that the mocha options are actually passed to the reporter when it is constructed. This means that you could also read a well namespaced field from there, eg:

``` javascript
config.mochaTest[name] = {
  options: {
    reporter: 'good-mocha-html-reporter',
    timeout: 60000,
    logErrors: true,
    goodMochaHtmlReporter: {
      path: directories.target,
      filename: name + '/test-results.html'
    }
  }
}
```

or something like that.

I think then in your code you may be able to do something like:

``` javascript
module.exports = function(runner, options) {
  localOptions = options.goodMochaHtmlReporter
  ...
```

not sure, how it all hangs together. I just remember having to add support for this in `grunt-mocha-test` because of changes in the way the standard `xunit` reporter worked.

**Comment by Gauge** [comment]
Adding an html output will be easy. Ill go ahead and add that later today.
As for the other stuff, it will take me a bit longer but you have given me
some good ideas.

**Comment by Gauge** [comment]
I have released a new version with a HTML_OUT mode that can be selected in
the config file. I am looking into a better way to configure the reporter.

**Comment by Gauge** [comment]
The module now takes options from the mocha options. Options are: savePath,
filename, mode. Let me know if you have any issue or requests.

Benjamin
