### ISSUE TITLE
Mocha-test options for good-mocha-html-reporter

### ISSUE THREAD

**Issue by DeChrish** [Gauge/html_table_reporter#3]
Current options is not supporting :  grunt-mocha-test
https://github.com/pghalliday/grunt-mocha-test

Scenario : We have common dev dependencies, and good-mocha-html-reporter added to it.

When we run the test using grunt, we are not able to locate the good-mocha-html-reporter.

Current Location : 
node_modules/build-plugin/node_modules/good-mocha-html-reporter

Expected:
node_module/good-mocha-html-reporter

**Comment by Gauge** [comment]
First let me state:
I have never used grunt-mocha-test nor have i installed my reporter as a dev dependency.

That aside i would still like to help you but need a little more information. Firstly I have never seen the build-plugin folder in any project i have worked on. I want to confirm that you are not installing this through grunt-mocha-test instead of the traditional package.json approach. If you are, I need to know how grunt does that, otherwise confirm the following...

Double check and make sure that:
1. You have the latest version 1.6.5 (as that is what i am running) 
2. Package is being installed from the package.json file in your root directory.
3. You have not installed your development copy as production by accident.

Hope that helps.

Edit:
I installed my reporter as a development module in the root of my test project and it successfully created a path to node_module/good-mocha-html-reporter

**Comment by DeChrish** [comment]
why we need to restrict path to node_module/good-mocha-html-reporter 
why can't  we look for any dir in node_module/?

Example in case :  node_modules/build-plugin/node_modules/good-mocha-html-reporter

Sorry : Issue title is misleading i guess. :(

**Comment by Gauge** [comment]
Are you able to get any other reporters the way you want to retrieve mine? To my knowledge, how the reporter is retrieved from from node_modules is part of the core nodejs/npm logic. If you are able to do this with another reporter let me know and ill figure out what it has that mine is missing.

**Comment by DeChrish** [comment]
i have not tried any other reports till date, looking for a good reporter like yours,

**Comment by Gauge** [comment]
If your still having a problem try using 'mocha-better-spec-reporter' and let me know if you can get that to work. the reporter doesn't do the same thing as mine but it should tell us if the problem at hand is something i'm doing wrong.
